name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'ISV2 deployment'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_TEMP_SERVER_PRIVATE_KEY }}

    - name: Connect and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.TEMP_SERVER_USER }}@${{ env.TEMP_SERVER_ADDRESS }} << 'EOF'
          cd auth-cyb
          cat <<EOT > .env.test
            DATABASE_URL = 'mysql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@localhost:3306/${{ secrets.DATABASE_NAME }}'
            
            NEXTAUTH_URL = '${{ env.NEXTAUTH_URL }}'
            NEXTAUTH_CALLBACK = '${{ secrets.NEXTAUTH_URL }}/pages/home'
            NEXTAUTH_SECRET = '${{ secrets.NEXTAUTH_SECRET }}'
            
            NEXTAUTH_GITHUB_CLIENT_ID = '${{ env.NEXTAUTH_GITHUB_CLIENT_ID }}'
            NEXTAUTH_GITHUB_CLIENT_SECRET = '${{ secrets.NEXTAUTH_GITHUB_CLIENT_SECRET }}'
            
            NEXT_PUBLIC_SANITY_API_VERSION = '${{ env.NEXT_PUBLIC_SANITY_API_VERSION }}'
            NEXT_PUBLIC_SANITY_DATASET = '${{ env.NEXT_PUBLIC_SANITY_DATASET }}'
            NEXT_PUBLIC_SANITY_PROJECT_ID = '${{ env.NEXT_PUBLIC_SANITY_PROJECT_ID }}'
          EOT
        EOF
